config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :expenditures
  resources :incomes
  resources :income_expenditure_statements
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'income_expenditure_statements#index'
end

app/models/income.rb
# frozen_string_literal: true

class Income < ApplicationRecord
  belongs_to :income_expenditure_statement

  DEFAULT_INCOME_CATEGORIES = %w[salary overtime housing_benefits].freeze
end

app/controllers/incomes_controller.rb
# frozen_string_literal: true

class IncomesController < ApplicationController
  before_action :set_income, only: %i[show edit update destroy]

  # GET /incomes or /incomes.json
  def index
    @incomes = Income.all
  end

  # GET /incomes/1 or /incomes/1.json
  def show; end

  # GET /incomes/new
  def new
    @income = Income.new
  end

  # GET /incomes/1/edit
  def edit; end

  # POST /incomes or /incomes.json
  def create
    @income = Income.new(income_params)

    respond_to do |format|
      if @income.save
        format.html { redirect_to income_url(@income), notice: 'Income was successfully created.' }
        format.json { render :show, status: :created, location: @income }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @income.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /incomes/1 or /incomes/1.json
  def update
    respond_to do |format|
      if @income.update(income_params)
        format.html { redirect_to income_url(@income), notice: 'Income was successfully updated.' }
        format.json { render :show, status: :ok, location: @income }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @income.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /incomes/1 or /incomes/1.json
  def destroy
    @income.destroy!

    respond_to do |format|
      format.html { redirect_to incomes_url, notice: 'Income was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_income
    @income = Income.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def income_params
    params.require(:income).permit(:earning, :category)
  end
end

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/views/incomes/_form.html.erb
<div class="nested-form-wrapper" data-new-record="<%= f.object.new_record?  %>" style= "display: flex">
  <div class="col-sm-6 p-1"> 
    <%= f.text_field :category, placeholder: "Type", class: "form-control" %>
  </div>
  <div class="col-sm-6 p-1"> 
    <%= f.number_field :earning, placeholder: "Amount", class: "form-control"  %>
  </div>

  <button type="button" data-action="nested-form#remove" class="btn btn-primary" >X</button>

  <%= f.hidden_field :_destroy %>
</div>

app/views/incomes/_income.html.erb
<div id="<%= dom_id income %>">
  <p>
    <strong>Earning:</strong>
    <%= income.earning %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= income.category %>
  </p>

</div>

app/views/incomes/edit.html.erb
<h1>Editing income</h1>

<%= render "form", income: @income %>

<br>

<div>
  <%= link_to "Show this income", @income %> |
  <%= link_to "Back to incomes", incomes_path %>
</div>

app/views/incomes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Incomes</h1>

<div id="incomes">
  <% @incomes.each do |income| %>
    <%= render income %>
    <p>
      <%= link_to "Show this income", income %>
    </p>
  <% end %>
</div>

<%= link_to "New income", new_income_path %>

app/views/incomes/new.html.erb
<h1>New income</h1>

<%= render "form", income: @income %>

<br>

<div>
  <%= link_to "Back to incomes", incomes_path %>
</div>

app/views/incomes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @income %>

<div>
  <%= link_to "Edit this income", edit_income_path(@income) %> |
  <%= link_to "Back to incomes", incomes_path %>

  <%= button_to "Destroy this income", @income, method: :delete %>
</div>