config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :expenditures
  resources :incomes
  resources :income_expenditure_statements
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'income_expenditure_statements#index'
end

app/models/income_expenditure_statement.rb
# frozen_string_literal: true

class IncomeExpenditureStatement < ApplicationRecord
  belongs_to :user
  has_many :incomes, dependent: :destroy
  accepts_nested_attributes_for :incomes, allow_destroy: true, reject_if: proc { |attributes|
                                                                            attributes['earning'].blank?
                                                                          }
  has_many :expenditures, dependent: :destroy
  accepts_nested_attributes_for :expenditures, allow_destroy: true, reject_if: proc { |attributes|
                                                                                 attributes['expense'].blank?
                                                                               }

  validates :user_id, presence: true
  validates :name, presence: true

  def rating
    begin
      ratio = expenditures.sum(:expense) * 100 / incomes.sum(:earning)
    rescue ZeroDivisionError
      ratio = 0
    end
    case ratio
    when ratio < 10
      'A'
    when (10..30)
      'B'
    when (31..50)
      'C'
    else
      'D'
    end
  end
end

app/controllers/income_expenditure_statements_controller.rb
# frozen_string_literal: true

class IncomeExpenditureStatementsController < ApplicationController
  include IncomeExpenditureStatementsHelper
  before_action :set_income_expenditure_statement, only: %i[show edit update destroy]

  # GET /income_expenditure_statements or /income_expenditure_statements.json
  def index
    @income_expenditure_statements = current_user.income_expenditure_statements
  end

  # GET /income_expenditure_statements/1 or /income_expenditure_statements/1.json
  def show; end

  # GET /income_expenditure_statements/new
  def new
    @income_expenditure_statement = current_user.income_expenditure_statements.new
    setup_incomes_and_expenditures
  end

  # GET /income_expenditure_statements/1/edit
  def edit; end

  # POST /income_expenditure_statements or /income_expenditure_statements.json
  def create
    @income_expenditure_statement = current_user.income_expenditure_statements.new(income_expenditure_statement_params)

    respond_to do |format|
      if @income_expenditure_statement.save
        format.html do
          redirect_to income_expenditure_statement_url(@income_expenditure_statement),
                      notice: 'Income expenditure statement was successfully created.'
        end
        format.json { render :show, status: :created, location: @income_expenditure_statement }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @income_expenditure_statement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /income_expenditure_statements/1 or /income_expenditure_statements/1.json
  def update
    respond_to do |format|
      if @income_expenditure_statement.update(income_expenditure_statement_params)
        format.html do
          redirect_to income_expenditure_statement_url(@income_expenditure_statement),
                      notice: 'Income expenditure statement was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @income_expenditure_statement }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @income_expenditure_statement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /income_expenditure_statements/1 or /income_expenditure_statements/1.json
  def destroy
    @income_expenditure_statement.destroy!

    respond_to do |format|
      format.html do
        redirect_to income_expenditure_statements_url,
                    notice: 'Income expenditure statement was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_income_expenditure_statement
    @income_expenditure_statement = IncomeExpenditureStatement.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def income_expenditure_statement_params
    params.require(:income_expenditure_statement).permit(:name, :user_id, incomes_attributes: %i[id category earning _destroy],
                                                                          expenditures_attributes: %i[id category expense _destroy])
  end
end

app/helpers/income_expenditure_statements_helper.rb
module IncomeExpenditureStatementsHelper

  def total_rows(income_expenditure_statement)
    [income_expenditure_statement.incomes.count, income_expenditure_statement.expenditures.count].max
  end

  def setup_incomes_and_expenditures
    if @income_expenditure_statement.new_record?
      @income_expenditure_statement.incomes.empty?
      Income::DEFAULT_INCOME_CATEGORIES.each do |category|
         @income_expenditure_statement.incomes.build(category: category)
      end
      Expenditure::DEFAULT_EXPENDITURE_CATEGORIES.each do |category| 
        @income_expenditure_statement.expenditures.build(category: category)
      end
    end
    
  end
end

app/views/income_expenditure_statements/_form.html.erb
<%= form_with(model: @income_expenditure_statement) do |form| %>
  <% if income_expenditure_statement.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(income_expenditure_statement.errors.count, "error") %> prohibited this income_expenditure_statement from being saved:</h2>

      <ul>
        <% income_expenditure_statement.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block", class: "form-label" %>
    <%= form.text_field :name, placeholder: "January", class: "form-control", required: true %>
  </div>
  

  <hr class="my-4">
  <div class="row g-3">
    <h4>Income (Monthly)</h4>
    <div data-controller="nested-form" data-nested-form-wrapper-selector-value=".nested-form-wrapper">
      <template data-nested-form-target="template">
        <%= form.fields_for :incomes, Income.new, child_index: 'NEW_RECORD' do |income_fields| %>
          <%= render "incomes/form", f: income_fields %>
        <% end %>
      </template>
      <%= form.fields_for :incomes do |income_form| %>
        <%= render "incomes/form", f: income_form %>
      <% end %>
      <div class="col-sm-12 p1">
        <div data-nested-form-target="target"></div>
        <button type="button" data-action="nested-form#add" class="btn btn-primary" >Add more incomes</button>
      </div>
    </div>
  </div>
  
  <hr class="my-4">
  <div class="row g-3">
    <h4>Expenditures (Monthly)</h4>
    <div data-controller="nested-form" data-nested-form-wrapper-selector-value=".nested-form-wrapper">
      <template data-nested-form-target="template">
        <%= form.fields_for :expenditures, Expenditure.new, child_index: 'NEW_RECORD' do |expenditure_fields| %>
          <%= render "expenditures/form", f: expenditure_fields %>
        <% end %>
      </template>
      <%= form.fields_for :expenditures do |expenditure_form| %>
        <%= render "expenditures/form", f: expenditure_form %>
      <% end %>
      <div class="col-sm-12 p1">
        <div data-nested-form-target="target"></div>
        <button type="button" data-action="nested-form#add" class="btn btn-primary" >Add more Expenditure</button>
      </div>
    </div>  
  </div>
  <hr class="my-4">
    <%= form.submit class: "w-100 btn btn-primary btn-lg" %>
  </div>
<% end %>

app/views/income_expenditure_statements/_income_expenditure_statement.html.erb
<div id="<%= dom_id income_expenditure_statement %>">
  <p>
    <strong>Name:</strong>
    <%= income_expenditure_statement.name %>
  </p>

  <p>
    <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">Income</th>
            <th scope="col">Amount</th>
            <th scope="col">Expenditure</th>
            <th scope="col">Amount</th>
          </tr>
        </thead>
        <tbody>
          <% max_rows = total_rows(income_expenditure_statement) %>
          <% max_rows.times do |index| %>
            <tr>
              <td><%= income_expenditure_statement.incomes[index]&.category %></td>
              <td><%= income_expenditure_statement.incomes[index]&.earning %></td>
              <td><%= income_expenditure_statement.expenditures[index]&.category %></td>
              <td><%= income_expenditure_statement.expenditures[index]&.expense %></td>
              <td>
            </tr>
          <% end %>
        </tbody>
      </table>
  </p>

  <div class="bd-callout bd-callout-warning">
    <strong>Rating:</strong>
    <%= income_expenditure_statement.rating %>
  </div>

</div>

app/views/income_expenditure_statements/edit.html.erb
<h1>Editing income expenditure statement</h1>

<%= render "form", income_expenditure_statement: @income_expenditure_statement %>

<br>

<div>
  <%= link_to "Show Rating", @income_expenditure_statement %> |
  <%= link_to "Back", income_expenditure_statements_path %>
</div>

app/views/income_expenditure_statements/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Income Expenditure Statements</h1>

<div id="income_expenditure_statements">
  <% if @income_expenditure_statements.blank? %>
    <p>You don't have any income expenditure statements.</p>
  <% else %>
    <% @income_expenditure_statements.each do |income_expenditure_statement| %>
      <%= render income_expenditure_statement %>
      <hr class="my-4">
      <p>
        <%#= link_to "Show this income expenditure statement", income_expenditure_statement %>
      </p>
    <% end %>
  <% end %>
</div>

<%= link_to "New Statement", new_income_expenditure_statement_path %>

app/views/income_expenditure_statements/new.html.erb
<h1>New income expenditure statement</h1>

<%= render "form", income_expenditure_statement: @income_expenditure_statement %>

<br>

<div>
  <%= link_to "Back to income expenditure statements", income_expenditure_statements_path %>
</div>

app/views/income_expenditure_statements/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @income_expenditure_statement %>

<div>
  <%= link_to "Edit", edit_income_expenditure_statement_path(@income_expenditure_statement) %> |
  <%= link_to "Back", income_expenditure_statements_path %>

  <%= button_to "Delete", @income_expenditure_statement, method: :delete, class: "btn btn-primary " %>
</div>